/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Papers */
        get: operations["list_papers_api_papers_get"];
        put?: never;
        /**
         * Upload Papers
         * @description Upload and parse PDFs. Each file gets its own result; one bad file never fails the batch.
         */
        post: operations["upload_papers_api_papers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper */
        get: operations["get_paper_api_papers__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Parsed Document
         * @description Full parsed output: text, page spans, sections, and traceable chunks.
         */
        get: operations["get_parsed_document_api_papers__paper_id__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Paper
         * @description Re-run parsing for a stored PDF (e.g. after changing chunking settings).
         */
        post: operations["process_paper_api_papers__paper_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Paper
         * @description Extract evidence-backed scientific knowledge from a parsed paper using the LLM.
         *
         *     By default runs in the background (202); poll `GET /papers/{paper_id}` for
         *     `extraction_status`, then read `GET /papers/{paper_id}/knowledge`.
         */
        post: operations["extract_paper_api_papers__paper_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Knowledge
         * @description The stored extraction result: entities, relations, evidence, and run metadata.
         */
        get: operations["get_knowledge_api_papers__paper_id__knowledge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/twin/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Paper
         * @description Merge a paper's extracted knowledge into the twin (idempotent; runs automatically
         *     after a successful extraction). Returns what was added, strengthened, changed, or removed.
         */
        post: operations["apply_paper_api_twin_papers__paper_id__post"];
        /**
         * Remove Paper
         * @description Remove a paper's contribution; shared entities keep other papers' support.
         */
        delete: operations["remove_paper_api_twin_papers__paper_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/twin/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Twin Summary */
        get: operations["twin_summary_api_twin_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/twin/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Twin Snapshot
         * @description The full twin as validated entities, relations (with evidence), and update history.
         */
        get: operations["twin_snapshot_api_twin_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/twin/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Twin Updates
         * @description Change history, newest first.
         */
        get: operations["twin_updates_api_twin_updates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Graph
         * @description Nodes and the edges between them, for graph visualization.
         */
        get: operations["graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Graph Node
         * @description A node with its edges, neighbors, and the full evidence behind them.
         */
        get: operations["graph_node_api_graph_nodes__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Evidence
         * @description Semantic search over indexed evidence quotes and chunks (local embeddings).
         */
        get: operations["search_evidence_api_evidence_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Author */
        Author: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Aliases */
            aliases?: string[];
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Author";
            /** Affiliation */
            affiliation?: string | null;
        };
        /** Body_upload_papers_api_papers_post */
        Body_upload_papers_api_papers_post: {
            /**
             * Files
             * @description One or more PDF files
             */
            files: string[];
        };
        /** Chunk */
        Chunk: {
            /** Id */
            id?: string;
            /** Paper Id */
            paper_id: string;
            /** Section Id */
            section_id?: string | null;
            /** Section Title */
            section_title?: string | null;
            /** Text */
            text: string;
            /**
             * Page
             * @description Page where the chunk starts
             */
            page?: number | null;
            /**
             * Page End
             * @description Page where the chunk ends
             */
            page_end?: number | null;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
        };
        /**
         * Comparison
         * @description A cross-paper table, e.g. methods x datasets with reported metric values.
         */
        Comparison: {
            /** Id */
            id?: string;
            /** Title */
            title: string;
            /**
             * Dimension
             * @description e.g. 'method_dataset', 'limitations'
             */
            dimension: string;
            /** Cells */
            cells?: components["schemas"]["ComparisonCell"][];
        };
        /** ComparisonCell */
        ComparisonCell: {
            /** Paper Id */
            paper_id: string;
            /** Method Id */
            method_id?: string | null;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Metric Id */
            metric_id?: string | null;
            /** Value */
            value?: string | number | null;
            /** Evidence Id */
            evidence_id?: string | null;
        };
        /** Contradiction */
        Contradiction: {
            /** Id */
            id?: string;
            /** Finding A Id */
            finding_a_id: string;
            /** Finding B Id */
            finding_b_id: string;
            /** Explanation */
            explanation: string;
            /**
             * Evidence
             * @description At least one quote per finding
             */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
        };
        /** Dataset */
        Dataset: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Aliases */
            aliases?: string[];
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Dataset";
        };
        /**
         * DroppedItem
         * @description An LLM-proposed item rejected during grounding, kept for transparency.
         */
        DroppedItem: {
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** Reason */
            reason: string;
        };
        /**
         * EntityType
         * @enum {string}
         */
        EntityType: "Paper" | "Author" | "Method" | "Dataset" | "Metric" | "Finding" | "Limitation" | "FutureWork" | "ResearchGap";
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id?: string;
            /** Paper Id */
            paper_id: string;
            /**
             * Quote
             * @description Verbatim text from the source paper
             */
            quote: string;
            /** Section */
            section?: string | null;
            /** Chunk Id */
            chunk_id?: string | null;
            span?: components["schemas"]["SourceSpan"] | null;
            /**
             * Extracted By
             * @description Agent that produced this evidence
             */
            extracted_by: string;
            /**
             * Model
             * @description LLM used, if any
             */
            model?: string | null;
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /** @default unverified */
            verification_status: components["schemas"]["VerificationStatus"];
            /** Verification Note */
            verification_note?: string | null;
        };
        /** ExtractionMeta */
        ExtractionMeta: {
            /** Provider */
            provider: string;
            /** Models */
            models?: string[];
            /** Prompt Version */
            prompt_version: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at?: string;
            stats?: components["schemas"]["ExtractionStats"];
            /** Dropped */
            dropped?: components["schemas"]["DroppedItem"][];
            /** Warnings */
            warnings?: string[];
        };
        /** ExtractionStats */
        ExtractionStats: {
            /**
             * Windows Total
             * @default 0
             */
            windows_total: number;
            /**
             * Windows Failed
             * @default 0
             */
            windows_failed: number;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /**
             * Items Proposed
             * @default 0
             */
            items_proposed: number;
            /**
             * Items Kept
             * @default 0
             */
            items_kept: number;
            /**
             * Items Dropped
             * @default 0
             */
            items_dropped: number;
            /**
             * Evidence Verified
             * @default 0
             */
            evidence_verified: number;
            /**
             * Evidence Flagged
             * @default 0
             */
            evidence_flagged: number;
            /**
             * Evidence Unverified
             * @default 0
             */
            evidence_unverified: number;
        };
        /**
         * ExtractionStatus
         * @enum {string}
         */
        ExtractionStatus: "running" | "completed" | "failed";
        /** Finding */
        Finding: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Aliases */
            aliases?: string[];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Paper Id */
            paper_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Finding";
        };
        /** FutureWork */
        FutureWork: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Aliases */
            aliases?: string[];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Paper Id */
            paper_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "FutureWork";
        };
        /**
         * GapSignal
         * @description Structured signals a research gap can be derived from (see AI_METHODOLOGY.md).
         * @enum {string}
         */
        GapSignal: "repeated_limitation" | "future_work" | "contradiction" | "missing_comparison" | "underexplored_metric" | "weak_evidence";
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            type: components["schemas"]["RelationType"];
            /** Source Id */
            source_id: string;
            source_type: components["schemas"]["EntityType"];
            /** Target Id */
            target_id: string;
            target_type: components["schemas"]["EntityType"];
            /** Paper Ids */
            paper_ids?: string[];
            /** Evidence Ids */
            evidence_ids?: string[];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /** Properties */
            properties?: {
                [key: string]: string | number | boolean | string[] | null;
            };
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            type: components["schemas"]["EntityType"];
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /** Description */
            description?: string | null;
            /** Paper Ids */
            paper_ids?: string[];
            /** Evidence Ids */
            evidence_ids?: string[];
            /** Properties */
            properties?: {
                [key: string]: string | number | boolean | string[] | null;
            };
        };
        /** GraphView */
        GraphView: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** App */
            app: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /** Llm Provider */
            llm_provider: string;
            /** Llm Configured */
            llm_configured: boolean;
            /** Graph Backend */
            graph_backend: string;
            /** Vector Backend */
            vector_backend: string;
        };
        /** Limitation */
        Limitation: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Aliases */
            aliases?: string[];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Paper Id */
            paper_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Limitation";
        };
        /** Method */
        Method: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Aliases */
            aliases?: string[];
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Method";
        };
        /** Metric */
        Metric: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Aliases */
            aliases?: string[];
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Metric";
            /** Higher Is Better */
            higher_is_better?: boolean | null;
        };
        /** NodeDetail */
        NodeDetail: {
            node: components["schemas"]["GraphNode"];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Neighbors */
            neighbors: components["schemas"]["GraphNode"][];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /**
         * PageSpan
         * @description Where one PDF page's text lives inside `ParsedDocument.text`.
         */
        PageSpan: {
            /** Page Number */
            page_number: number;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
        };
        /** Paper */
        Paper: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Aliases */
            aliases?: string[];
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Paper";
            /** Year */
            year?: number | null;
            /** Venue */
            venue?: string | null;
            /** Doi */
            doi?: string | null;
            /** Url */
            url?: string | null;
            /** File Name */
            file_name?: string | null;
            /** Abstract */
            abstract?: string | null;
        };
        /**
         * PaperKnowledge
         * @description Structured, evidence-backed knowledge extracted from one paper (input to the KG).
         */
        PaperKnowledge: {
            paper: components["schemas"]["Paper"];
            research_problem?: components["schemas"]["ResearchStatement"] | null;
            /** Research Questions */
            research_questions?: components["schemas"]["ResearchStatement"][];
            /** Methods */
            methods?: components["schemas"]["Method"][];
            /** Datasets */
            datasets?: components["schemas"]["Dataset"][];
            /** Metrics */
            metrics?: components["schemas"]["Metric"][];
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Limitations */
            limitations?: components["schemas"]["Limitation"][];
            /** Future Work */
            future_work?: components["schemas"]["FutureWork"][];
            /** Relations */
            relations?: components["schemas"]["Relation"][];
            meta: components["schemas"]["ExtractionMeta"];
        };
        /**
         * PaperRecord
         * @description Ingestion bookkeeping for one uploaded PDF.
         */
        PaperRecord: {
            /** Paper Id */
            paper_id: string;
            /** File Name */
            file_name: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** @default uploaded */
            status: components["schemas"]["PaperStatus"];
            /** Error */
            error?: string | null;
            /** Title */
            title?: string | null;
            /** Parser */
            parser?: string | null;
            /** Page Count */
            page_count?: number | null;
            /** Section Count */
            section_count?: number | null;
            /** Chunk Count */
            chunk_count?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Parsed At */
            parsed_at?: string | null;
            extraction_status?: components["schemas"]["ExtractionStatus"] | null;
            /** Extraction Error */
            extraction_error?: string | null;
            /** Extracted At */
            extracted_at?: string | null;
            /** Twin Updated At */
            twin_updated_at?: string | null;
            /** Twin Error */
            twin_error?: string | null;
        };
        /**
         * PaperStatus
         * @enum {string}
         */
        PaperStatus: "uploaded" | "parsed" | "failed";
        /** ParsedDocument */
        ParsedDocument: {
            /** Paper Id */
            paper_id: string;
            /** File Name */
            file_name: string;
            /** Title */
            title?: string | null;
            /**
             * Parser
             * @description e.g. 'pymupdf' or 'docling'
             */
            parser: string;
            /** Page Count */
            page_count: number;
            /** Text */
            text: string;
            /** Pages */
            pages?: components["schemas"]["PageSpan"][];
            /** Sections */
            sections?: components["schemas"]["Section"][];
            /** Chunks */
            chunks?: components["schemas"]["Chunk"][];
        };
        /**
         * PossibleDuplicate
         * @description A similar-but-not-merged pair, surfaced for human review instead of auto-merging.
         */
        PossibleDuplicate: {
            entity_type: components["schemas"]["EntityType"];
            /** Name */
            name: string;
            /** Candidate Id */
            candidate_id: string;
            /** Candidate Name */
            candidate_name: string;
            /** Score */
            score: number;
        };
        /** RankedEntity */
        RankedEntity: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Paper Count */
            paper_count: number;
        };
        /** Relation */
        Relation: {
            /** Id */
            id?: string;
            type: components["schemas"]["RelationType"];
            /** Source Id */
            source_id: string;
            source_type: components["schemas"]["EntityType"];
            /** Target Id */
            target_id: string;
            target_type: components["schemas"]["EntityType"];
            /**
             * Properties
             * @description e.g. REPORTS: {value: 0.91, unit: 'F1', dataset_id: ..., method_id: ...}
             */
            properties?: {
                [key: string]: string | number | boolean | null;
            };
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
        };
        /**
         * RelationType
         * @enum {string}
         */
        RelationType: "AUTHORED" | "CITES" | "USES" | "EVALUATES" | "REPORTS" | "CLAIMS" | "STATES" | "COMPARES" | "IMPROVES" | "CONTRADICTS" | "SUGGESTS";
        /**
         * ResearchGap
         * @description A cross-paper gap. Never speculative: it must cite signals, entities, and evidence.
         */
        ResearchGap: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Aliases */
            aliases?: string[];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ResearchGap";
            /** Rationale */
            rationale: string;
            /** Signals */
            signals: components["schemas"]["GapSignal"][];
            /** Supporting Entity Ids */
            supporting_entity_ids: string[];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
        };
        /**
         * ResearchStatement
         * @description A research problem or question, grounded in the paper like any other claim.
         */
        ResearchStatement: {
            /** Text */
            text: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /**
         * ResolutionDecision
         * @description How an extracted entity name was mapped to a canonical graph node.
         */
        ResolutionDecision: {
            entity_type: components["schemas"]["EntityType"];
            /** Original Name */
            original_name: string;
            /** Canonical Id */
            canonical_id: string;
            /** Canonical Name */
            canonical_name: string;
            /**
             * Method
             * @enum {string}
             */
            method: "new" | "exact" | "normalized" | "acronym" | "fuzzy";
            /** Confidence */
            confidence: number;
        };
        /** Section */
        Section: {
            /** Id */
            id?: string;
            /** Title */
            title: string;
            /** @default other */
            kind: components["schemas"]["SectionKind"];
            /** Page Start */
            page_start?: number | null;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
        };
        /**
         * SectionKind
         * @enum {string}
         */
        SectionKind: "front_matter" | "abstract" | "introduction" | "related_work" | "methods" | "experiments" | "results" | "discussion" | "limitations" | "future_work" | "conclusion" | "acknowledgments" | "references" | "appendix" | "other";
        /**
         * SourceSpan
         * @description Location of a quote inside the parsed paper text.
         */
        SourceSpan: {
            /** Page */
            page?: number | null;
            /** Char Start */
            char_start?: number | null;
            /** Char End */
            char_end?: number | null;
        };
        /** TwinSnapshot */
        TwinSnapshot: {
            /** Domain */
            domain: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Entities */
            entities?: (components["schemas"]["Paper"] | components["schemas"]["Author"] | components["schemas"]["Method"] | components["schemas"]["Dataset"] | components["schemas"]["Metric"] | components["schemas"]["Finding"] | components["schemas"]["Limitation"] | components["schemas"]["FutureWork"] | components["schemas"]["ResearchGap"])[];
            /** Relations */
            relations?: components["schemas"]["Relation"][];
            /** Contradictions */
            contradictions?: components["schemas"]["Contradiction"][];
            /** Comparisons */
            comparisons?: components["schemas"]["Comparison"][];
            /** Updates */
            updates?: components["schemas"]["TwinUpdate"][];
        };
        /** TwinStats */
        TwinStats: {
            /** Entity Counts */
            entity_counts: {
                [key: string]: number;
            };
            /** Relation Count */
            relation_count: number;
            /** Contradiction Count */
            contradiction_count: number;
            /** Verified Evidence */
            verified_evidence: number;
            /** Flagged Evidence */
            flagged_evidence: number;
        };
        /**
         * TwinSummary
         * @description Dashboard-level view of the Research Digital Twin.
         */
        TwinSummary: {
            /** Domain */
            domain: string;
            /** Paper Count */
            paper_count: number;
            stats: components["schemas"]["TwinStats"];
            /** Unverified Evidence */
            unverified_evidence: number;
            /** Relation Counts */
            relation_counts: {
                [key: string]: number;
            };
            /** Indexed Vectors */
            indexed_vectors: number;
            /** Top Methods */
            top_methods: components["schemas"]["RankedEntity"][];
            /** Top Datasets */
            top_datasets: components["schemas"]["RankedEntity"][];
            /** Top Metrics */
            top_metrics: components["schemas"]["RankedEntity"][];
            last_update?: components["schemas"]["TwinUpdate"] | null;
        };
        /**
         * TwinUpdate
         * @description Changelog entry recording how one ingestion run changed the twin.
         *
         *     - added: new nodes/edges
         *     - strengthened: existing nodes/edges that gained supporting papers or evidence
         *     - changed: existing nodes/edges whose content changed without gaining support
         *       (e.g. new aliases, or re-extraction replaced their evidence)
         *     - removed: nodes/edges no longer supported by any paper (e.g. after re-extraction)
         */
        TwinUpdate: {
            /** Id */
            id?: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Operation
             * @default apply
             * @enum {string}
             */
            operation: "apply" | "remove";
            /** Paper Ids */
            paper_ids?: string[];
            /** Added Entity Ids */
            added_entity_ids?: string[];
            /** Strengthened Entity Ids */
            strengthened_entity_ids?: string[];
            /** Changed Entity Ids */
            changed_entity_ids?: string[];
            /** Removed Entity Ids */
            removed_entity_ids?: string[];
            /** Added Relation Ids */
            added_relation_ids?: string[];
            /** Strengthened Relation Ids */
            strengthened_relation_ids?: string[];
            /** Changed Relation Ids */
            changed_relation_ids?: string[];
            /** Removed Relation Ids */
            removed_relation_ids?: string[];
            /** New Contradiction Ids */
            new_contradiction_ids?: string[];
            /** New Gap Ids */
            new_gap_ids?: string[];
            /**
             * Resolutions
             * @description Entity names merged into existing canonical nodes
             */
            resolutions?: components["schemas"]["ResolutionDecision"][];
            /** Possible Duplicates */
            possible_duplicates?: components["schemas"]["PossibleDuplicate"][];
            /**
             * Evidence Indexed
             * @default 0
             */
            evidence_indexed: number;
            /**
             * Chunks Indexed
             * @default 0
             */
            chunks_indexed: number;
            /** Summary */
            summary?: string | null;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Results */
            results: components["schemas"]["UploadResult"][];
        };
        /**
         * UploadResult
         * @description Outcome for one file in a multi-file upload. Exactly one of `paper`/`error` is set.
         */
        UploadResult: {
            /** File Name */
            file_name: string;
            paper?: components["schemas"]["PaperRecord"] | null;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
            error?: components["schemas"]["ErrorDetail"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VectorHit */
        VectorHit: {
            /** Score */
            score: number;
            payload: components["schemas"]["VectorPayload"];
        };
        /**
         * VectorPayload
         * @description Metadata stored with every vector, so a hit always traces back to its source.
         */
        VectorPayload: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "chunk" | "evidence";
            /** Paper Id */
            paper_id: string;
            /** Text */
            text: string;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Page */
            page?: number | null;
            /** Page End */
            page_end?: number | null;
            /** Section */
            section?: string | null;
            /** Char Start */
            char_start?: number | null;
            /** Char End */
            char_end?: number | null;
            /** Evidence Id */
            evidence_id?: string | null;
            /** Entity Id */
            entity_id?: string | null;
            /** Entity Type */
            entity_type?: string | null;
            /** Claim */
            claim?: string | null;
            /** Verification Status */
            verification_status?: string | null;
            /** Confidence */
            confidence?: number | null;
        };
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "unverified" | "verified" | "flagged";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_papers_api_papers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperRecord"][];
                };
            };
        };
    };
    upload_papers_api_papers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_papers_api_papers_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_api_papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_parsed_document_api_papers__paper_id__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_paper_api_papers__paper_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_paper_api_papers__paper_id__extract_post: {
        parameters: {
            query?: {
                /** @description Run synchronously and return when done */
                wait?: boolean;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Extraction finished (wait=true) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_api_papers__paper_id__knowledge_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperKnowledge"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_paper_api_twin_papers__paper_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwinUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_paper_api_twin_papers__paper_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwinUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    twin_summary_api_twin_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwinSummary"];
                };
            };
        };
    };
    twin_snapshot_api_twin_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwinSnapshot"];
                };
            };
        };
    };
    twin_updates_api_twin_updates_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwinUpdate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_api_graph_get: {
        parameters: {
            query?: {
                paper_id?: string | null;
                /** @description Filter node types */
                type?: components["schemas"]["EntityType"][] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_node_api_graph_nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_evidence_api_evidence_search_get: {
        parameters: {
            query: {
                q: string;
                paper_id?: string | null;
                kind?: ("chunk" | "evidence") | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VectorHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
